theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  search:
    active: false  
  logo:
    footer: "/assets/images/logo-footer.svg"
  posts:
    index:
      layout: grid
  menu:
    primary:
      level_2:
        title:
          active: true